application.name=ms-dacs-bff

dacs.exceptions.code-prefix=bff

spring.application.name=bff
spring.profiles.active=@activeProfile@

server.tomcat.basedir=.
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.prefix=ms_dacs2025_access_
server.tomcat.accesslog.suffix=.log
server.tomcat.accesslog.file-date-format=yyyy-MM-dd
server.tomcat.accesslog.pattern=%t %a "%r" %s (%D ms)

keycloak.base-url=http://localhost:8080/auth
keycloak.realm=dacs
keycloak.admin-token=REEMPLAZA_CON_TOKEN_ADMIN
